export const LOGIN = '/'
export const PASS_RECOVERY = '/recovery'
export const MAIN_PAGE = '/:branch/main'
export const ADD_CATEGORY = '/:branch/category'
export const ADD_PRODUCT = '/:branch/product'
export const BRANCH_PAGE = '/branch_select'
